version: '3'

services:
  mongodb:
    image: mongo:4.0.20
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=roots
      - MONGO_INITDB_ROOT_PASSWORD=roots
    volumes:
      - .docker/mongo/mongoDatabaseFiles:/data/db

  tmsapi:
    build:
      context: ./TMS-API
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  uploadapi:
    build:
      context: ./Upload-API
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/uploads/






