version: '3'

services:
  mongodb:
    image: mongo:4.0.20
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=roots
      - MONGO_INITDB_ROOT_PASSWORD=roots
    volumes:
      - ./mongo/mongoDatabaseFiles:/data/db